name: 'Resolve vercel preview url'
description: 'Resolve the preview url of a specific vercel project'
inputs:
  vercel_token:
      description: 'The Vercel token to authenticate with'
      required: true
  team_id:
    description: 'The vercel team id'
    required: true
  project_id:
    description: 'The vercel project id'
    required: true
  github_commit_sha:
    description: 'The commit sha you want to filter on'
    required: true

outputs:
  url: # id of output
    description: 'The vercel deployment url'
runs:
  using: 'node12'
  main: 'dist/index.js'
